####################################################################################
# 系统运行相关配置
####################################################################################
system:
  # 监听端口
  listen: 0.0.0.0
  # 监听地址
  port: 12580

####################################################################################
# 日志配置
####################################################################################
log:
  # 系统日志
  system:
    # 是否打印日志到文件
    enabled: true
    # 日志等级，参考 zapcore.Level（-1<=level<=5，-1 / DEBUG）
    level: -1
    # 日志保存目录和文件名称
    path: logs/system
    # 日志切割配置，单位 M
    max-size: 100
    # 日志保留天数
    max-age: 7
    # 日志保留个数
    max-backups: 10
    # 是否压缩
    compress: false
  # 访问日志
  access:
    enabled: true
    # 日志等级，参考 zapcore.Level（-1<=level<=5，-1 / DEBUG）
    level: -1
    # 日志保存目录和文件名称
    path: logs/access
    # 日志切割配置，单位 M
    max-size: 100
    # 日志保留天数
    max-age: 7
    # 日志保留个数
    max-backups: 10
    # 是否压缩
    compress: false
